version: "3.8"

services:
  backend:
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000

    env_file:
      - .env.dev
    networks:
      - default
    volumes:
      - .test-results:/app/.test-results
    depends_on:
      - postgres
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.ci
    volumes:
      - .test-results:/app/.test-results

  postgres:
    env_file:
      - .env.dev
    networks:
      - default