version: "3.8"

services:
  backend:
    build:
      context: ./backend
    image: registry.digitalocean.com/demoprojectreg/backend:${VERSION}
    command: python manage.py runserver 0.0.0.0:8000

    env_file:
      - .env.dev
    networks:
      - default
    volumes:
      - .test-results:/app/.test-results
    depends_on:
      - postgres

  frontend-test:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.ci
    volumes:
      - .test-results:/app/.test-results

  frontend:
    image: registry.digitalocean.com/demoprojectreg/frontend:${VERSION}
    build:
      context: ./frontend
      dockerfile: ./Dockerfile

  postgres:
    env_file:
      - .env.dev
    networks:
      - default