import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {useEffect, useState} from "react";
import {getPosts, sendPost} from "../api";
import PostsList from "../components/posts-list";

export async function getServerSideProps() {
  return { props: {} }
}

export default function Home() {
  const [posts, setPosts] = useState([]);
  const [currentPost, setCurrentPost] = useState('');

  useEffect(async () => {
    const postsResponse = await getPosts();
    setPosts(postsResponse);
  }, [])

  const handleSubmit = async (event) => {
    event.preventDefault();
    const returnedPost = await sendPost(currentPost);
    setPosts([returnedPost].concat(posts));
    setCurrentPost('');
  };

  const handlePostChange = (event) => {
    setCurrentPost(event.target.value);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3 className={styles.title}>
          Message board
        </h3>

        <div className={styles.description}>
          <form onSubmit={handleSubmit}>
            <input type="text" name="message-input" placeholder="Input your text and press enter" value={currentPost} onChange={handlePostChange}/>
          </form>
        </div>

        <div className={styles.description}>
          <PostsList posts={posts} />
        </div>
      </main>
    </div>
  )
}
